import { appPath } from '../basePath.js'

export const games = [
  {
    id: 'card-game',
    title: 'Kartenspiel',
    description: 'Der digitale Punkteblock für euer physisches Stichspiel.',
    path: appPath('/kartenspiel'),
    artwork: appPath('/assets/cards-on-felt.webp'),
    available: true,
    rooms: null,
    resumePath: appPath('/kartenspiel/spielen'),
  },
  {
    id: 'doppelwort',
    title: 'Imposter',
    description: 'Hinweise geben, bluffen und den Imposter enttarnen.',
    path: appPath('/imposter'),
    artwork: appPath('/assets/doppelwort-table.webp'),
    available: true,
    rooms: { gameKey: 'doppelwort', localFallback: true, realtime: true },
    theme: 'night',
    resumePath: appPath('/imposter/raum'),
  },
  {
    id: 'kniffel',
    title: 'Kniffel',
    description: 'Klassisch würfeln – komplett digital oder mit echtem Würfel und sicherem Punkteblock.',
    path: appPath('/kniffel'),
    artwork: appPath('/assets/kniffel-table.webp'),
    available: true,
    rooms: { gameKey: 'kniffel', localFallback: true, realtime: true },
    theme: 'wine',
    resumePath: appPath('/kniffel/spiel'),
  },
  {
    id: 'battleship',
    title: 'Schiffe versenken',
    description: 'Zwei geheime Flotten, ein gemeinsames Gerät und zehn Reihen Hochspannung.',
    path: appPath('/schiffe-versenken'),
    artwork: appPath('/assets/battleship-table.svg'),
    available: true,
    rooms: null,
    theme: 'ocean',
    resumePath: appPath('/schiffe-versenken/spiel'),
  },
  {
    id: 'werewolf',
    title: 'Werwolf',
    description: 'Eine geführte Nacht im Dorf – mit geheimen Rollen, Hexe, Seherin und Jäger.',
    path: appPath('/werwolf'),
    artwork: appPath('/assets/werewolf-table.svg'),
    available: true,
    rooms: null,
    theme: 'moon',
    resumePath: appPath('/werwolf/spiel'),
  },
  {
    id: 'memory',
    title: 'Memory',
    description: 'Deine eigenen Bilder werden zu einem persönlichen Kartenpaar-Spiel.',
    path: appPath('/memory'),
    artwork: appPath('/assets/memory/memory-table.svg'),
    available: true,
    requiresMemoryAssets: true,
    rooms: null,
    theme: 'memory',
    resumePath: appPath('/memory/spielen'),
  },
]
