const categoryLabels = {
  de: {
    animals: 'Tiere',
    food: 'Essen',
    vehicles: 'Fahrzeuge',
    sports: 'Sport',
    jobs: 'Berufe',
    nature: 'Natur',
    social: 'Internet & Social Media',
    memes: 'Memes & Netzkultur',
  },
  en: {
    animals: 'Animals',
    food: 'Food',
    vehicles: 'Vehicles',
    sports: 'Sports',
    jobs: 'Jobs',
    nature: 'Nature',
    social: 'Internet & Social Media',
    memes: 'Memes & Internet Culture',
  },
}

const hintLabels = {
  de: {
    animals: 'Lebewesen',
    food: 'Alltag',
    vehicles: 'Unterwegs',
    sports: 'Freizeit',
    jobs: 'Menschen',
    nature: 'Draußen',
    social: 'Online',
    memes: 'Internetkultur',
  },
  en: {
    animals: 'Living things',
    food: 'Everyday life',
    vehicles: 'On the move',
    sports: 'Leisure',
    jobs: 'People',
    nature: 'Outdoors',
    social: 'Online',
    memes: 'Internet culture',
  },
}

const germanPairs = [
  ['animals', 'Katze', 'Tiger'],
  ['animals', 'Hund', 'Wolf'],
  ['animals', 'Pferd', 'Zebra'],
  ['animals', 'Ente', 'Gans'],
  ['animals', 'Biene', 'Wespe'],
  ['animals', 'Adler', 'Falke'],
  ['animals', 'Delfin', 'Wal'],
  ['animals', 'Hase', 'Igel'],
  ['animals', 'Frosch', 'Kröte'],
  ['animals', 'Schaf', 'Ziege'],
  ['animals', 'Löwe', 'Leopard'],
  ['animals', 'Eule', 'Uhu'],
  ['animals', 'Krokodil', 'Schlange'],
  ['animals', 'Robbe', 'Seelöwe'],
  ['animals', 'Krabbe', 'Hummer'],
  ['animals', 'Pinguin', 'Papageientaucher'],
  ['animals', 'Maus', 'Ratte'],
  ['animals', 'Igel', 'Stachelschwein'],
  ['animals', 'Lama', 'Esel'],
  ['animals', 'Schwan', 'Flamingo'],
  ['food', 'Pizza', 'Burger'],
  ['food', 'Kaffee', 'Tee'],
  ['food', 'Apfel', 'Birne'],
  ['food', 'Reis', 'Nudeln'],
  ['food', 'Kuchen', 'Eis'],
  ['food', 'Honig', 'Marmelade'],
  ['food', 'Butter', 'Olivenöl'],
  ['food', 'Suppe', 'Eintopf'],
  ['food', 'Pfannkuchen', 'Waffel'],
  ['food', 'Ketchup', 'Senf'],
  ['food', 'Orange', 'Banane'],
  ['food', 'Brot', 'Brötchen'],
  ['food', 'Schokolade', 'Kakao'],
  ['food', 'Käse', 'Joghurt'],
  ['food', 'Pommes', 'Kroketten'],
  ['food', 'Eis', 'Pudding'],
  ['food', 'Gurke', 'Tomate'],
  ['food', 'Steak', 'Schnitzel'],
  ['food', 'Müsli', 'Haferbrei'],
  ['food', 'Limonade', 'Eistee'],
  ['vehicles', 'Flugzeug', 'Hubschrauber'],
  ['vehicles', 'Fahrrad', 'Motorrad'],
  ['vehicles', 'Auto', 'Taxi'],
  ['vehicles', 'Bus', 'Straßenbahn'],
  ['vehicles', 'Zug', 'U-Bahn'],
  ['vehicles', 'Segelboot', 'Heißluftballon'],
  ['vehicles', 'LKW', 'Transporter'],
  ['vehicles', 'Roller', 'Moped'],
  ['vehicles', 'Kanu', 'Schlitten'],
  ['vehicles', 'Traktor', 'Mähdrescher'],
  ['vehicles', 'Raumschiff', 'Rakete'],
  ['vehicles', 'Fähre', 'Hubschrauber'],
  ['vehicles', 'Heißluftballon', 'Rakete'],
  ['vehicles', 'Polizeiauto', 'Bagger'],
  ['vehicles', 'Bagger', 'Kran'],
  ['vehicles', 'Skateboard', 'Longboard'],
  ['vehicles', 'Schlitten', 'Bob'],
  ['vehicles', 'Wohnmobil', 'Wohnwagen'],
  ['vehicles', 'U-Boot', 'Raumschiff'],
  ['vehicles', 'Limousine', 'Sportwagen'],
  ['sports', 'Fußball', 'Handball'],
  ['sports', 'Tennis', 'Badminton'],
  ['sports', 'Skifahren', 'Snowboarden'],
  ['sports', 'Boxen', 'Ringen'],
  ['sports', 'Schwimmen', 'Tauchen'],
  ['sports', 'Basketball', 'Volleyball'],
  ['sports', 'Golf', 'Bowling'],
  ['sports', 'Joggen', 'Sprinten'],
  ['sports', 'Surfen', 'Klettern'],
  ['sports', 'Klettern', 'Turnen'],
  ['sports', 'Fechten', 'Kendo'],
  ['sports', 'Rudern', 'Paddeln'],
  ['sports', 'Eishockey', 'Basketball'],
  ['sports', 'Turnen', 'Akrobatik'],
  ['sports', 'Darts', 'Bowling'],
  ['sports', 'Baseball', 'Cricket'],
  ['sports', 'Judo', 'Karate'],
  ['sports', 'Tischtennis', 'Squash'],
  ['sports', 'Reiten', 'Polo'],
  ['sports', 'Triathlon', 'Marathon'],
  ['jobs', 'Arzt', 'Sanitäter'],
  ['jobs', 'Lehrer', 'Professor'],
  ['jobs', 'Koch', 'Bäcker'],
  ['jobs', 'Polizist', 'Detektiv'],
  ['jobs', 'Pilot', 'Astronaut'],
  ['jobs', 'Architekt', 'Bauingenieur'],
  ['jobs', 'Fotograf', 'Kameramann'],
  ['jobs', 'Schauspieler', 'Moderator'],
  ['jobs', 'Gärtner', 'Florist'],
  ['jobs', 'Richter', 'Anwalt'],
  ['jobs', 'Mechaniker', 'Elektriker'],
  ['jobs', 'Journalist', 'Autor'],
  ['jobs', 'Friseur', 'Visagist'],
  ['jobs', 'Kellner', 'Barkeeper'],
  ['jobs', 'Musiker', 'Dirigent'],
  ['jobs', 'Programmierer', 'Designer'],
  ['jobs', 'Landwirt', 'Förster'],
  ['jobs', 'Zahnarzt', 'Optiker'],
  ['jobs', 'Schneider', 'Schuhmacher'],
  ['jobs', 'Feuerwehrmann', 'Pilot'],
  ['nature', 'Sonne', 'Mond'],
  ['nature', 'Fluss', 'See'],
  ['nature', 'Berg', 'Vulkan'],
  ['nature', 'Wald', 'Dschungel'],
  ['nature', 'Regen', 'Schnee'],
  ['nature', 'Blitz', 'Donner'],
  ['nature', 'Strand', 'Wüste'],
  ['nature', 'Insel', 'Halbinsel'],
  ['nature', 'Höhle', 'Schlucht'],
  ['nature', 'Quelle', 'Wasserfall'],
  ['nature', 'Wiese', 'Steppe'],
  ['nature', 'Nebel', 'Wolke'],
  ['nature', 'Rose', 'Tulpe'],
  ['nature', 'Eiche', 'Buche'],
  ['nature', 'Kristall', 'Diamant'],
  ['nature', 'Ozean', 'Wüste'],
  ['nature', 'Gletscher', 'Vulkan'],
  ['nature', 'Tal', 'Ebene'],
  ['nature', 'Stern', 'Planet'],
  ['nature', 'Muschel', 'Koralle'],
  ['social', 'TikTok', 'Twitch'],
  ['social', 'Instagram', 'WhatsApp'],
  ['social', 'YouTube', 'Spotify'],
  ['social', 'Story', 'Podcast'],
  ['social', 'Like', 'Hashtag'],
  ['social', 'Influencer', 'Moderator'],
  ['social', 'Filter', 'Emoji'],
  ['social', 'Reel', 'Livestream'],
  ['social', 'Follower', 'Kommentar'],
  ['social', 'Algorithmus', 'Trend'],
  ['social', 'Viralvideo', 'Sprachnachricht'],
  ['social', 'Selfie', 'Unboxing'],
  ['social', 'Duett', 'Tutorial'],
  ['social', 'Feed', 'Chat'],
  ['social', 'Discord', 'Snapchat'],
  ['social', 'BeReal', 'Pinterest'],
  ['social', 'Challenge', 'Rezept'],
  ['social', 'Creator', 'Zuschauer'],
  ['social', 'Scrollen', 'Tippen'],
  ['social', 'Thumbnail', 'Profilbild'],
  ['memes', 'Rickroll', 'Doge'],
  ['memes', 'Grumpy Cat', 'Drake-Meme'],
  ['memes', 'Spider-Man-Meme', 'Distracted Boyfriend'],
  ['memes', 'Facepalm', 'NPC'],
  ['memes', 'Fail', 'Plot Twist'],
  ['memes', 'Prank', 'POV'],
  ['memes', 'Cringe', 'Main Character'],
  ['memes', 'Sus', 'Noob'],
  ['memes', 'Troll', 'Side Eye'],
  ['memes', 'GIF', 'Insiderwitz'],
  ['memes', 'Lag', 'Screenshot'],
  ['memes', 'Glitch', 'Tutorial'],
  ['memes', 'Speedrun', 'Selfie'],
  ['memes', 'Emoji', 'Copypasta'],
  ['memes', 'Keyboard Cat', 'Minions'],
  ['memes', 'Stonks', 'YOLO'],
  ['memes', 'Reaction', 'Hashtag'],
  ['memes', 'Viral', 'Kommentar'],
  ['memes', 'Sticker', 'Sprachnachricht'],
  ['memes', 'Meme', 'Trend'],
]

const englishPairs = [
  ['animals', 'Cat', 'Tiger'],
  ['animals', 'Dog', 'Wolf'],
  ['animals', 'Horse', 'Zebra'],
  ['animals', 'Duck', 'Goose'],
  ['animals', 'Bee', 'Wasp'],
  ['animals', 'Eagle', 'Falcon'],
  ['animals', 'Dolphin', 'Whale'],
  ['animals', 'Hare', 'Hedgehog'],
  ['animals', 'Frog', 'Toad'],
  ['animals', 'Sheep', 'Goat'],
  ['animals', 'Lion', 'Leopard'],
  ['animals', 'Owl', 'Eagle owl'],
  ['animals', 'Crocodile', 'Snake'],
  ['animals', 'Seal', 'Sea lion'],
  ['animals', 'Crab', 'Lobster'],
  ['animals', 'Penguin', 'Puffin'],
  ['animals', 'Mouse', 'Rat'],
  ['animals', 'Hedgehog', 'Porcupine'],
  ['animals', 'Llama', 'Donkey'],
  ['animals', 'Swan', 'Flamingo'],
  ['food', 'Pizza', 'Burger'],
  ['food', 'Coffee', 'Tea'],
  ['food', 'Apple', 'Pear'],
  ['food', 'Rice', 'Noodles'],
  ['food', 'Cake', 'Ice cream'],
  ['food', 'Honey', 'Jam'],
  ['food', 'Butter', 'Olive oil'],
  ['food', 'Soup', 'Stew'],
  ['food', 'Pancake', 'Waffle'],
  ['food', 'Ketchup', 'Mustard'],
  ['food', 'Orange', 'Banana'],
  ['food', 'Bread', 'Roll'],
  ['food', 'Chocolate', 'Cocoa'],
  ['food', 'Cheese', 'Yogurt'],
  ['food', 'Fries', 'Hash browns'],
  ['food', 'Ice cream', 'Pudding'],
  ['food', 'Cucumber', 'Tomato'],
  ['food', 'Steak', 'Cutlet'],
  ['food', 'Granola', 'Porridge'],
  ['food', 'Lemonade', 'Iced tea'],
  ['vehicles', 'Airplane', 'Helicopter'],
  ['vehicles', 'Bicycle', 'Motorcycle'],
  ['vehicles', 'Car', 'Taxi'],
  ['vehicles', 'Bus', 'Tram'],
  ['vehicles', 'Train', 'Subway'],
  ['vehicles', 'Sailboat', 'Hot-air balloon'],
  ['vehicles', 'Truck', 'Van'],
  ['vehicles', 'Scooter', 'Moped'],
  ['vehicles', 'Canoe', 'Sled'],
  ['vehicles', 'Tractor', 'Harvester'],
  ['vehicles', 'Spaceship', 'Rocket'],
  ['vehicles', 'Ferry', 'Helicopter'],
  ['vehicles', 'Hot-air balloon', 'Rocket'],
  ['vehicles', 'Police car', 'Excavator'],
  ['vehicles', 'Excavator', 'Crane'],
  ['vehicles', 'Skateboard', 'Longboard'],
  ['vehicles', 'Sled', 'Bobsled'],
  ['vehicles', 'Campervan', 'Caravan'],
  ['vehicles', 'Submarine', 'Spaceship'],
  ['vehicles', 'Limousine', 'Sports car'],
  ['sports', 'Soccer', 'Handball'],
  ['sports', 'Tennis', 'Badminton'],
  ['sports', 'Skiing', 'Snowboarding'],
  ['sports', 'Boxing', 'Wrestling'],
  ['sports', 'Swimming', 'Diving'],
  ['sports', 'Basketball', 'Volleyball'],
  ['sports', 'Golf', 'Bowling'],
  ['sports', 'Jogging', 'Sprinting'],
  ['sports', 'Surfing', 'Climbing'],
  ['sports', 'Climbing', 'Gymnastics'],
  ['sports', 'Fencing', 'Kendo'],
  ['sports', 'Rowing', 'Paddling'],
  ['sports', 'Ice hockey', 'Basketball'],
  ['sports', 'Gymnastics', 'Acrobatics'],
  ['sports', 'Darts', 'Bowling'],
  ['sports', 'Baseball', 'Cricket'],
  ['sports', 'Judo', 'Karate'],
  ['sports', 'Table tennis', 'Squash'],
  ['sports', 'Horse riding', 'Polo'],
  ['sports', 'Triathlon', 'Marathon'],
  ['jobs', 'Doctor', 'Paramedic'],
  ['jobs', 'Teacher', 'Professor'],
  ['jobs', 'Chef', 'Baker'],
  ['jobs', 'Police officer', 'Detective'],
  ['jobs', 'Pilot', 'Astronaut'],
  ['jobs', 'Architect', 'Civil engineer'],
  ['jobs', 'Photographer', 'Camera operator'],
  ['jobs', 'Actor', 'Presenter'],
  ['jobs', 'Gardener', 'Florist'],
  ['jobs', 'Judge', 'Lawyer'],
  ['jobs', 'Mechanic', 'Electrician'],
  ['jobs', 'Journalist', 'Author'],
  ['jobs', 'Hairdresser', 'Makeup artist'],
  ['jobs', 'Waiter', 'Bartender'],
  ['jobs', 'Musician', 'Conductor'],
  ['jobs', 'Programmer', 'Designer'],
  ['jobs', 'Farmer', 'Forester'],
  ['jobs', 'Dentist', 'Optician'],
  ['jobs', 'Tailor', 'Shoemaker'],
  ['jobs', 'Firefighter', 'Pilot'],
  ['nature', 'Sun', 'Moon'],
  ['nature', 'River', 'Lake'],
  ['nature', 'Mountain', 'Volcano'],
  ['nature', 'Forest', 'Jungle'],
  ['nature', 'Rain', 'Snow'],
  ['nature', 'Lightning', 'Thunder'],
  ['nature', 'Beach', 'Desert'],
  ['nature', 'Island', 'Peninsula'],
  ['nature', 'Cave', 'Canyon'],
  ['nature', 'Spring', 'Waterfall'],
  ['nature', 'Meadow', 'Steppe'],
  ['nature', 'Fog', 'Cloud'],
  ['nature', 'Rose', 'Tulip'],
  ['nature', 'Oak', 'Beech'],
  ['nature', 'Crystal', 'Diamond'],
  ['nature', 'Ocean', 'Desert'],
  ['nature', 'Glacier', 'Volcano'],
  ['nature', 'Valley', 'Plain'],
  ['nature', 'Star', 'Planet'],
  ['nature', 'Shell', 'Coral'],
  ['social', 'TikTok', 'Twitch'],
  ['social', 'Instagram', 'WhatsApp'],
  ['social', 'YouTube', 'Spotify'],
  ['social', 'Story', 'Podcast'],
  ['social', 'Like', 'Hashtag'],
  ['social', 'Influencer', 'Moderator'],
  ['social', 'Filter', 'Emoji'],
  ['social', 'Reel', 'Livestream'],
  ['social', 'Follower', 'Comment'],
  ['social', 'Algorithm', 'Trend'],
  ['social', 'Viral video', 'Voice message'],
  ['social', 'Selfie', 'Unboxing'],
  ['social', 'Duet', 'Tutorial'],
  ['social', 'Feed', 'Chat'],
  ['social', 'Discord', 'Snapchat'],
  ['social', 'BeReal', 'Pinterest'],
  ['social', 'Challenge', 'Recipe'],
  ['social', 'Creator', 'Viewer'],
  ['social', 'Scrolling', 'Typing'],
  ['social', 'Thumbnail', 'Profile picture'],
  ['memes', 'Rickroll', 'Doge'],
  ['memes', 'Grumpy Cat', 'Drake Meme'],
  ['memes', 'Spider-Man Meme', 'Distracted Boyfriend'],
  ['memes', 'Facepalm', 'NPC'],
  ['memes', 'Fail', 'Plot twist'],
  ['memes', 'Prank', 'POV'],
  ['memes', 'Cringe', 'Main Character'],
  ['memes', 'Sus', 'Noob'],
  ['memes', 'Troll', 'Side eye'],
  ['memes', 'GIF', 'Inside joke'],
  ['memes', 'Lag', 'Screenshot'],
  ['memes', 'Glitch', 'Tutorial'],
  ['memes', 'Speedrun', 'Selfie'],
  ['memes', 'Emoji', 'Copypasta'],
  ['memes', 'Keyboard Cat', 'Minions'],
  ['memes', 'Stonks', 'YOLO'],
  ['memes', 'Reaction', 'Hashtag'],
  ['memes', 'Viral', 'Comment'],
  ['memes', 'Sticker', 'Voice message'],
  ['memes', 'Meme', 'Trend'],
]

function buildWordPairs(language, pairs) {
  return pairs.map(([category, crew, imposter], index) => ({
    id: `${language}-${String(index + 1).padStart(3, '0')}`,
    language,
    category,
    categoryLabel: categoryLabels[language][category],
    crew,
    imposter,
    hint: hintLabels[language][category],
  }))
}

export const WORD_PAIRS = {
  de: buildWordPairs('de', germanPairs),
  en: buildWordPairs('en', englishPairs),
}

export function getWordPairs(language = 'de', category = 'all') {
  const pairs = WORD_PAIRS[language] ?? WORD_PAIRS.de
  return category === 'all' ? pairs : pairs.filter((pair) => pair.category === category)
}
