const categoryLabels = {
  de: {
    animals: 'Tiere',
    food: 'Essen',
    vehicles: 'Fahrzeuge',
    sports: 'Sport',
    jobs: 'Berufe',
    nature: 'Natur',
  },
  en: {
    animals: 'Animals',
    food: 'Food',
    vehicles: 'Vehicles',
    sports: 'Sports',
    jobs: 'Jobs',
    nature: 'Nature',
  },
}

const germanPairs = [
  ['animals', 'Katze', 'Tiger'],
  ['animals', 'Hund', 'Wolf'],
  ['animals', 'Pferd', 'Zebra'],
  ['animals', 'Ente', 'Gans'],
  ['animals', 'Biene', 'Wespe'],
  ['animals', 'Adler', 'Falke'],
  ['animals', 'Delfin', 'Wal'],
  ['animals', 'Hase', 'Kaninchen'],
  ['animals', 'Frosch', 'Kröte'],
  ['animals', 'Schaf', 'Ziege'],
  ['animals', 'Löwe', 'Leopard'],
  ['animals', 'Eule', 'Uhu'],
  ['animals', 'Krokodil', 'Alligator'],
  ['animals', 'Robbe', 'Seelöwe'],
  ['animals', 'Krabbe', 'Hummer'],
  ['animals', 'Pinguin', 'Papageientaucher'],
  ['animals', 'Maus', 'Ratte'],
  ['animals', 'Igel', 'Stachelschwein'],
  ['animals', 'Lama', 'Alpaka'],
  ['animals', 'Schwan', 'Flamingo'],
  ['food', 'Pizza', 'Burger'],
  ['food', 'Kaffee', 'Tee'],
  ['food', 'Apfel', 'Birne'],
  ['food', 'Reis', 'Nudeln'],
  ['food', 'Kuchen', 'Torte'],
  ['food', 'Honig', 'Marmelade'],
  ['food', 'Butter', 'Margarine'],
  ['food', 'Suppe', 'Eintopf'],
  ['food', 'Pfannkuchen', 'Waffel'],
  ['food', 'Ketchup', 'Senf'],
  ['food', 'Orange', 'Mandarine'],
  ['food', 'Brot', 'Brötchen'],
  ['food', 'Schokolade', 'Kakao'],
  ['food', 'Käse', 'Joghurt'],
  ['food', 'Pommes', 'Kroketten'],
  ['food', 'Eis', 'Sorbet'],
  ['food', 'Gurke', 'Zucchini'],
  ['food', 'Steak', 'Schnitzel'],
  ['food', 'Müsli', 'Haferbrei'],
  ['food', 'Limonade', 'Eistee'],
  ['vehicles', 'Flugzeug', 'Hubschrauber'],
  ['vehicles', 'Fahrrad', 'Motorrad'],
  ['vehicles', 'Auto', 'Taxi'],
  ['vehicles', 'Bus', 'Straßenbahn'],
  ['vehicles', 'Zug', 'U-Bahn'],
  ['vehicles', 'Segelboot', 'Motorboot'],
  ['vehicles', 'LKW', 'Transporter'],
  ['vehicles', 'Roller', 'Moped'],
  ['vehicles', 'Kanu', 'Kajak'],
  ['vehicles', 'Traktor', 'Mähdrescher'],
  ['vehicles', 'Raumschiff', 'Rakete'],
  ['vehicles', 'Fähre', 'Kreuzfahrtschiff'],
  ['vehicles', 'Heißluftballon', 'Zeppelin'],
  ['vehicles', 'Polizeiauto', 'Feuerwehrauto'],
  ['vehicles', 'Bagger', 'Kran'],
  ['vehicles', 'Skateboard', 'Longboard'],
  ['vehicles', 'Schlitten', 'Bob'],
  ['vehicles', 'Wohnmobil', 'Wohnwagen'],
  ['vehicles', 'U-Boot', 'Tauchboot'],
  ['vehicles', 'Limousine', 'Sportwagen'],
  ['sports', 'Fußball', 'Handball'],
  ['sports', 'Tennis', 'Badminton'],
  ['sports', 'Skifahren', 'Snowboarden'],
  ['sports', 'Boxen', 'Ringen'],
  ['sports', 'Schwimmen', 'Tauchen'],
  ['sports', 'Basketball', 'Volleyball'],
  ['sports', 'Golf', 'Minigolf'],
  ['sports', 'Joggen', 'Sprinten'],
  ['sports', 'Surfen', 'Kitesurfen'],
  ['sports', 'Klettern', 'Bouldern'],
  ['sports', 'Fechten', 'Kendo'],
  ['sports', 'Rudern', 'Paddeln'],
  ['sports', 'Eishockey', 'Feldhockey'],
  ['sports', 'Turnen', 'Akrobatik'],
  ['sports', 'Darts', 'Bowling'],
  ['sports', 'Baseball', 'Cricket'],
  ['sports', 'Judo', 'Karate'],
  ['sports', 'Tischtennis', 'Squash'],
  ['sports', 'Reiten', 'Polo'],
  ['sports', 'Triathlon', 'Marathon'],
  ['jobs', 'Arzt', 'Sanitäter'],
  ['jobs', 'Lehrer', 'Professor'],
  ['jobs', 'Koch', 'Bäcker'],
  ['jobs', 'Polizist', 'Detektiv'],
  ['jobs', 'Pilot', 'Astronaut'],
  ['jobs', 'Architekt', 'Bauingenieur'],
  ['jobs', 'Fotograf', 'Kameramann'],
  ['jobs', 'Schauspieler', 'Moderator'],
  ['jobs', 'Gärtner', 'Florist'],
  ['jobs', 'Richter', 'Anwalt'],
  ['jobs', 'Mechaniker', 'Elektriker'],
  ['jobs', 'Journalist', 'Autor'],
  ['jobs', 'Friseur', 'Visagist'],
  ['jobs', 'Kellner', 'Barkeeper'],
  ['jobs', 'Musiker', 'Dirigent'],
  ['jobs', 'Programmierer', 'Designer'],
  ['jobs', 'Landwirt', 'Förster'],
  ['jobs', 'Zahnarzt', 'Kieferorthopäde'],
  ['jobs', 'Schneider', 'Schuhmacher'],
  ['jobs', 'Feuerwehrmann', 'Bergretter'],
  ['nature', 'Sonne', 'Mond'],
  ['nature', 'Fluss', 'See'],
  ['nature', 'Berg', 'Vulkan'],
  ['nature', 'Wald', 'Dschungel'],
  ['nature', 'Regen', 'Schnee'],
  ['nature', 'Blitz', 'Donner'],
  ['nature', 'Strand', 'Wüste'],
  ['nature', 'Insel', 'Halbinsel'],
  ['nature', 'Höhle', 'Schlucht'],
  ['nature', 'Quelle', 'Wasserfall'],
  ['nature', 'Wiese', 'Steppe'],
  ['nature', 'Nebel', 'Wolke'],
  ['nature', 'Rose', 'Tulpe'],
  ['nature', 'Eiche', 'Buche'],
  ['nature', 'Kristall', 'Diamant'],
  ['nature', 'Ozean', 'Meer'],
  ['nature', 'Gletscher', 'Eisberg'],
  ['nature', 'Tal', 'Ebene'],
  ['nature', 'Stern', 'Planet'],
  ['nature', 'Muschel', 'Koralle'],
]

const englishPairs = [
  ['animals', 'Cat', 'Tiger'],
  ['animals', 'Dog', 'Wolf'],
  ['animals', 'Horse', 'Zebra'],
  ['animals', 'Duck', 'Goose'],
  ['animals', 'Bee', 'Wasp'],
  ['animals', 'Eagle', 'Falcon'],
  ['animals', 'Dolphin', 'Whale'],
  ['animals', 'Hare', 'Rabbit'],
  ['animals', 'Frog', 'Toad'],
  ['animals', 'Sheep', 'Goat'],
  ['animals', 'Lion', 'Leopard'],
  ['animals', 'Owl', 'Eagle owl'],
  ['animals', 'Crocodile', 'Alligator'],
  ['animals', 'Seal', 'Sea lion'],
  ['animals', 'Crab', 'Lobster'],
  ['animals', 'Penguin', 'Puffin'],
  ['animals', 'Mouse', 'Rat'],
  ['animals', 'Hedgehog', 'Porcupine'],
  ['animals', 'Llama', 'Alpaca'],
  ['animals', 'Swan', 'Flamingo'],
  ['food', 'Pizza', 'Burger'],
  ['food', 'Coffee', 'Tea'],
  ['food', 'Apple', 'Pear'],
  ['food', 'Rice', 'Noodles'],
  ['food', 'Cake', 'Pie'],
  ['food', 'Honey', 'Jam'],
  ['food', 'Butter', 'Margarine'],
  ['food', 'Soup', 'Stew'],
  ['food', 'Pancake', 'Waffle'],
  ['food', 'Ketchup', 'Mustard'],
  ['food', 'Orange', 'Tangerine'],
  ['food', 'Bread', 'Roll'],
  ['food', 'Chocolate', 'Cocoa'],
  ['food', 'Cheese', 'Yogurt'],
  ['food', 'Fries', 'Hash browns'],
  ['food', 'Ice cream', 'Sorbet'],
  ['food', 'Cucumber', 'Zucchini'],
  ['food', 'Steak', 'Cutlet'],
  ['food', 'Granola', 'Porridge'],
  ['food', 'Lemonade', 'Iced tea'],
  ['vehicles', 'Airplane', 'Helicopter'],
  ['vehicles', 'Bicycle', 'Motorcycle'],
  ['vehicles', 'Car', 'Taxi'],
  ['vehicles', 'Bus', 'Tram'],
  ['vehicles', 'Train', 'Subway'],
  ['vehicles', 'Sailboat', 'Motorboat'],
  ['vehicles', 'Truck', 'Van'],
  ['vehicles', 'Scooter', 'Moped'],
  ['vehicles', 'Canoe', 'Kayak'],
  ['vehicles', 'Tractor', 'Harvester'],
  ['vehicles', 'Spaceship', 'Rocket'],
  ['vehicles', 'Ferry', 'Cruise ship'],
  ['vehicles', 'Hot-air balloon', 'Zeppelin'],
  ['vehicles', 'Police car', 'Fire engine'],
  ['vehicles', 'Excavator', 'Crane'],
  ['vehicles', 'Skateboard', 'Longboard'],
  ['vehicles', 'Sled', 'Bobsled'],
  ['vehicles', 'Campervan', 'Caravan'],
  ['vehicles', 'Submarine', 'Diving bell'],
  ['vehicles', 'Limousine', 'Sports car'],
  ['sports', 'Soccer', 'Handball'],
  ['sports', 'Tennis', 'Badminton'],
  ['sports', 'Skiing', 'Snowboarding'],
  ['sports', 'Boxing', 'Wrestling'],
  ['sports', 'Swimming', 'Diving'],
  ['sports', 'Basketball', 'Volleyball'],
  ['sports', 'Golf', 'Mini golf'],
  ['sports', 'Jogging', 'Sprinting'],
  ['sports', 'Surfing', 'Kitesurfing'],
  ['sports', 'Climbing', 'Bouldering'],
  ['sports', 'Fencing', 'Kendo'],
  ['sports', 'Rowing', 'Paddling'],
  ['sports', 'Ice hockey', 'Field hockey'],
  ['sports', 'Gymnastics', 'Acrobatics'],
  ['sports', 'Darts', 'Bowling'],
  ['sports', 'Baseball', 'Cricket'],
  ['sports', 'Judo', 'Karate'],
  ['sports', 'Table tennis', 'Squash'],
  ['sports', 'Horse riding', 'Polo'],
  ['sports', 'Triathlon', 'Marathon'],
  ['jobs', 'Doctor', 'Paramedic'],
  ['jobs', 'Teacher', 'Professor'],
  ['jobs', 'Chef', 'Baker'],
  ['jobs', 'Police officer', 'Detective'],
  ['jobs', 'Pilot', 'Astronaut'],
  ['jobs', 'Architect', 'Civil engineer'],
  ['jobs', 'Photographer', 'Camera operator'],
  ['jobs', 'Actor', 'Presenter'],
  ['jobs', 'Gardener', 'Florist'],
  ['jobs', 'Judge', 'Lawyer'],
  ['jobs', 'Mechanic', 'Electrician'],
  ['jobs', 'Journalist', 'Author'],
  ['jobs', 'Hairdresser', 'Makeup artist'],
  ['jobs', 'Waiter', 'Bartender'],
  ['jobs', 'Musician', 'Conductor'],
  ['jobs', 'Programmer', 'Designer'],
  ['jobs', 'Farmer', 'Forester'],
  ['jobs', 'Dentist', 'Orthodontist'],
  ['jobs', 'Tailor', 'Shoemaker'],
  ['jobs', 'Firefighter', 'Mountain rescuer'],
  ['nature', 'Sun', 'Moon'],
  ['nature', 'River', 'Lake'],
  ['nature', 'Mountain', 'Volcano'],
  ['nature', 'Forest', 'Jungle'],
  ['nature', 'Rain', 'Snow'],
  ['nature', 'Lightning', 'Thunder'],
  ['nature', 'Beach', 'Desert'],
  ['nature', 'Island', 'Peninsula'],
  ['nature', 'Cave', 'Canyon'],
  ['nature', 'Spring', 'Waterfall'],
  ['nature', 'Meadow', 'Steppe'],
  ['nature', 'Fog', 'Cloud'],
  ['nature', 'Rose', 'Tulip'],
  ['nature', 'Oak', 'Beech'],
  ['nature', 'Crystal', 'Diamond'],
  ['nature', 'Ocean', 'Sea'],
  ['nature', 'Glacier', 'Iceberg'],
  ['nature', 'Valley', 'Plain'],
  ['nature', 'Star', 'Planet'],
  ['nature', 'Shell', 'Coral'],
]

function buildWordPairs(language, pairs) {
  return pairs.map(([category, crew, imposter], index) => ({
    id: `${language}-${String(index + 1).padStart(3, '0')}`,
    language,
    category,
    categoryLabel: categoryLabels[language][category],
    crew,
    imposter,
    hint: categoryLabels[language][category],
  }))
}

export const WORD_PAIRS = {
  de: buildWordPairs('de', germanPairs),
  en: buildWordPairs('en', englishPairs),
}

export function getWordPairs(language = 'de', category = 'all') {
  const pairs = WORD_PAIRS[language] ?? WORD_PAIRS.de
  return category === 'all' ? pairs : pairs.filter((pair) => pair.category === category)
}

